### ISSUE TITLE
Feature request: Ability to pass allowed routes for monorepository sites

### ISSUE THREAD

**Issue by phil-lgr** [netlify/git-gateway#38]
**- Do you want to request a *feature* or report a *bug*?**

Feature

**- What is the current behavior?**

Netlify CMS allow us to pass the following options to git-gateway:

```
backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
```

now from netlify's identity settings the repository is set up:

![image](https://user-images.githubusercontent.com/9644867/68437263-6f268280-018e-11ea-9b9f-35ca1531ee1f.png)

So that means that users from that site have access to the following scopes:

```
 /repos/:owner/:name/git/
 /repos/:owner/:name/contents/
 /repos/:owner/:name/pulls/
 /repos/:owner/:name/branches/
```

**- What is the expected behavior?**

Mono-repository are increasingly popular and people want to have multiple sites under one git repository.

for example, it's very common to have multiple site under packages 

```
packages/
 - site1
 - site2
```

I would like to be able to pass specific paths to git-gateway in order to restrict a user from site1 to only content of site1, something like: 

```
 /repos/:owner/:name/git/
 /repos/:owner/:name/contents/packages/site1 # restrict to site1 dir only
 /repos/:owner/:name/pulls/
 /repos/:owner/:name/branches/
```

Maybe something like:

```yaml
# config.yml for site 1
backend:
  name: git-gateway
  accept_roles: 
    - admin
    - editor
  accept_content_routes: # <------ restrict content access to those paths only
    - packages/site1

# config.yml for site 1
backend:
  name: git-gateway
  accept_roles: 
    - admin
    - editor
  accept_content_routes: # <------ restrict content access to those paths only
    - packages/site2
```
